/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * SimpleSectionPanel.java
 *
 * Created on 18.10.2011, 09:05:47
 */
package de.cismet.tools.gui.jbands;

import java.awt.BorderLayout;
import java.awt.Dimension;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * DOCUMENT ME!
 *
 * @author   thorsten
 * @version  $Revision$, $Date$
 */
public class SimpleSpotPanel extends JPanel {

    //~ Instance fields --------------------------------------------------------

    private ImageIcon up = new javax.swing.ImageIcon(getClass().getResource(
                "/de/cismet/tools/gui/jbands/spotMarkUp.png"));
    private ImageIcon down = new javax.swing.ImageIcon(getClass().getResource(
                "/de/cismet/tools/gui/jbands/spotMarkDown.png"));

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form SimpleSectionPanel.
     */
    public SimpleSpotPanel() {
        initComponents();
        setLayout(new BorderLayout());
        add(new JLabel(up), BorderLayout.CENTER);
        setPreferredSize(new Dimension(up.getIconWidth(), up.getIconHeight()));
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setPreferredSize(new java.awt.Dimension(0, 0));

        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 213, Short.MAX_VALUE));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 160, Short.MAX_VALUE));
    } // </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
