/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * SimpleSectionPanel.java
 *
 * Created on 18.10.2011, 09:05:47
 */
package de.cismet.tools.gui.jbands;

import java.awt.Color;

import javax.swing.JPanel;

import de.cismet.tools.gui.jbands.interfaces.BandMemberProvider;

/**
 * DOCUMENT ME!
 *
 * @author   thorsten
 * @version  $Revision$, $Date$
 */
public class SimpleSectionPanel extends JPanel {

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form SimpleSectionPanel.
     */
    public SimpleSectionPanel() {
        this(Color.getHSBColor((float)Math.random(), 0.85f, 1.0f));
    }

    /**
     * Creates a new SimpleSectionPanel object.
     *
     * @param  c  DOCUMENT ME!
     */
    public SimpleSectionPanel(final Color c) {
        initComponents();
        setBackground(c);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setBackground(new java.awt.Color(255, 51, 0));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1, 1));

        final org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 1, Short.MAX_VALUE));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 1, Short.MAX_VALUE));
    } // </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
