/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * LinkStyleBreadCrumbGui.java
 *
 * Created on 09.11.2009, 11:45:16
 */
package de.cismet.tools.gui.breadcrumb;

import org.jdesktop.swingx.JXHyperlink;

import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 * DOCUMENT ME!
 *
 * @author   thorsten
 * @version  $Revision$, $Date$
 */
public class LinkStyleBreadCrumbGui extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    JXHyperlink first = null;

    private final org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(this.getClass());
    private BreadCrumbModel breadCrumbModel = new DefaultBreadCrumbModel();
    private ImageIcon arrow = new javax.swing.ImageIcon(getClass().getResource(
                "/de/cismet/tools/gui/res/arrowRight.png")); // NOI18N
    private boolean showFirstCrumbAlone = false;

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form LinkStyleBreadCrumbGui.
     */
    public LinkStyleBreadCrumbGui() {
        initComponents();
    }

    /**
     * Creates a new LinkStyleBreadCrumbGui object.
     *
     * @param  breadCrumbModel  DOCUMENT ME!
     */
    public LinkStyleBreadCrumbGui(final BreadCrumbModel breadCrumbModel) {
        this();
        setBreadCrumbModel(breadCrumbModel);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setOpaque(false);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public BreadCrumbModel getBreadCrumbModel() {
        return breadCrumbModel;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  breadCrumbModel  DOCUMENT ME!
     */
    public void setBreadCrumbModel(final BreadCrumbModel breadCrumbModel) {
        this.breadCrumbModel = breadCrumbModel;
        breadCrumbModel.addBreadCrumbModelListener(new AbstractBreadCrumbModelListener() {

                @Override
                public void breadCrumbModelChanged(final BreadCrumbEvent bce) {
                    LinkStyleBreadCrumbGui.this.removeAll();
                    LinkStyleBreadCrumbGui.this.revalidate();
                    final BreadCrumbModel m = bce.getSource();
                    final List<BreadCrumb> l = m.getAllCrumbs();
                    for (final BreadCrumb bc : l) {
                        addToGui(bc);
                    }
                }

                @Override
                public void breadCrumbAdded(final BreadCrumbEvent bce) {
                    final BreadCrumb bc = bce.getBreadCrumb();
                    addToGui(bc);
                }
            });
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public boolean isShowFirstCrumbAlone() {
        return showFirstCrumbAlone;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  showFirstCrumbAlone  DOCUMENT ME!
     */
    public void setShowFirstCrumbAlone(final boolean showFirstCrumbAlone) {
        this.showFirstCrumbAlone = showFirstCrumbAlone;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  bc  DOCUMENT ME!
     */
    private void addToGui(final BreadCrumb bc) {
        if ((breadCrumbModel.getSize() > 0) && (breadCrumbModel.getFirstCrumb() != bc)) {
            final JLabel arrowL = new JLabel(arrow);
            LinkStyleBreadCrumbGui.this.add(arrowL);
        }

        final JXHyperlink bcLink = new JXHyperlink(bc);
        bcLink.setClickedColor(bcLink.getUnclickedColor());
        bcLink.setFocusPainted(false);
        LinkStyleBreadCrumbGui.this.add(bcLink);
        if (!showFirstCrumbAlone) {
            if (breadCrumbModel.getSize() == 1) {
                first = bcLink;
                first.setVisible(false);
            } else {
                first.setVisible(true);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
