/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * SimplestBreadCrumbGui.java
 *
 * Created on 07.11.2009, 21:18:58
 */
package de.cismet.tools.gui.breadcrumb;

import java.util.List;

import javax.swing.JButton;

/**
 * DOCUMENT ME!
 *
 * @author   thorsten
 * @version  $Revision$, $Date$
 */
public class SimplestBreadCrumbGui extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    private BreadCrumbModel breadCrumbModel = null;

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form SimplestBreadCrumbGui.
     */
    public SimplestBreadCrumbGui() {
        initComponents();
        setBreadCrumbModel(new DefaultBreadCrumbModel());
    }

    /**
     * Creates a new SimplestBreadCrumbGui object.
     *
     * @param  breadCrumbModel  DOCUMENT ME!
     */
    public SimplestBreadCrumbGui(final BreadCrumbModel breadCrumbModel) {
        this();
        setBreadCrumbModel(breadCrumbModel);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @param  breadCrumbModel  DOCUMENT ME!
     */
    public void setBreadCrumbModel(final BreadCrumbModel breadCrumbModel) {
        this.breadCrumbModel = breadCrumbModel;
        this.breadCrumbModel.addBreadCrumbModelListener(new AbstractBreadCrumbModelListener() {

                @Override
                public void breadCrumbModelChanged(final BreadCrumbEvent bce) {
                    SimplestBreadCrumbGui.this.removeAll();
                    SimplestBreadCrumbGui.this.revalidate();
                    final BreadCrumbModel m = bce.getSource();
                    final List<BreadCrumb> l = m.getAllCrumbs();
                    for (final BreadCrumb bc : l) {
                        final JButton bcButton = new JButton(bc);
                        SimplestBreadCrumbGui.this.add(bcButton);
                    }
                }

                @Override
                public void breadCrumbAdded(final BreadCrumbEvent bce) {
                    final JButton bcButton = new JButton(bce.getBreadCrumb());
                    SimplestBreadCrumbGui.this.add(bcButton);
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setBackground(new java.awt.Color(102, 255, 102));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    } // </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
