/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.commons.gui.protocol.impl;

import java.awt.Component;

import de.cismet.commons.gui.protocol.AbstractProtocolStepPanel;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class CommentProtocolStepPanel extends AbstractProtocolStepPanel {

    //~ Instance fields --------------------------------------------------------

    private final CommentProtocolStep commentProtocolStep;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form CommentProtocolStepPanel.
     *
     * @param  commentProtocolStep  DOCUMENT ME!
     */
    public CommentProtocolStepPanel(final CommentProtocolStep commentProtocolStep) {
        this.commentProtocolStep = commentProtocolStep;

        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        org.openide.awt.Mnemonics.setLocalizedText(lblTitle, org.openide.util.NbBundle.getMessage(CommentProtocolStepPanel.class, "CommentProtocolStepPanel.lblTitle.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblIcon, org.openide.util.NbBundle.getMessage(CommentProtocolStepPanel.class, "CommentProtocolStepPanel.lblIcon.text")); // NOI18N

        setLayout(new java.awt.GridBagLayout());

        jTextPane1.setText(commentProtocolStep.getMessage());
        jScrollPane1.setViewportView(jTextPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Component getIconComponent() {
        return lblIcon;
    }

    @Override
    public Component getTitleComponent() {
        return lblTitle;
    }
}
