/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.tools.gui;

import de.cismet.tools.gui.log4jquickconfig.Log4JQuickConfig;

/**
 * DOCUMENT ME!
 *
 * @author   thorsten.hell@cismet.de
 * @version  $Revision$, $Date$
 */
public class NewJFrame extends javax.swing.JFrame {

    //~ Instance fields --------------------------------------------------------

    private final org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(this.getClass());

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cbxDebug;
    private javax.swing.JRadioButton cbxError;
    private javax.swing.JRadioButton cbxFatal;
    private javax.swing.JButton cmdDebug;
    private javax.swing.JButton cmdError;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form NewJFrame.
     */
    public NewJFrame() {
        initComponents();
        configLog4J();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        cmdDebug = new javax.swing.JButton();
        cmdError = new javax.swing.JButton();
        cbxDebug = new javax.swing.JRadioButton();
        cbxError = new javax.swing.JRadioButton();
        cbxFatal = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cmdDebug.setText(org.openide.util.NbBundle.getMessage(NewJFrame.class, "NewJFrame.cmdDebug.text")); // NOI18N
        cmdDebug.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    cmdDebugActionPerformed(evt);
                }
            });
        getContentPane().add(cmdDebug);
        cmdDebug.setBounds(90, 160, 80, 29);

        cmdError.setText(org.openide.util.NbBundle.getMessage(NewJFrame.class, "NewJFrame.cmdError.text")); // NOI18N
        cmdError.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    cmdErrorActionPerformed(evt);
                }
            });
        getContentPane().add(cmdError);
        cmdError.setBounds(180, 160, 80, 29);

        cbxDebug.setSelected(true);
        cbxDebug.setText(org.openide.util.NbBundle.getMessage(NewJFrame.class, "NewJFrame.cbxDebug.text")); // NOI18N
        cbxDebug.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    cbxDebugActionPerformed(evt);
                }
            });
        getContentPane().add(cbxDebug);
        cbxDebug.setBounds(140, 70, 180, 22);

        cbxError.setText(org.openide.util.NbBundle.getMessage(NewJFrame.class, "NewJFrame.cbxError.text")); // NOI18N
        cbxError.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    cbxErrorActionPerformed(evt);
                }
            });
        getContentPane().add(cbxError);
        cbxError.setBounds(140, 90, 160, 22);

        cbxFatal.setText(org.openide.util.NbBundle.getMessage(NewJFrame.class, "NewJFrame.cbxFatal.text")); // NOI18N
        cbxFatal.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    cbxFatalActionPerformed(evt);
                }
            });
        getContentPane().add(cbxFatal);
        cbxFatal.setBounds(140, 110, 140, 22);

        final java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width - 408) / 2, (screenSize.height - 235) / 2, 408, 235);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void cmdErrorActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cmdErrorActionPerformed
        log.error("Error");                                                      // NOI18N
    }                                                                            //GEN-LAST:event_cmdErrorActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void cbxFatalActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cbxFatalActionPerformed
        cbxDebug.setSelected(false);
        cbxError.setSelected(false);
        cbxFatal.setSelected(true);
        configLog4J();
    }                                                                            //GEN-LAST:event_cbxFatalActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void cbxErrorActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cbxErrorActionPerformed
        cbxDebug.setSelected(false);
        cbxError.setSelected(true);
        cbxFatal.setSelected(false);
        configLog4J();
    }                                                                            //GEN-LAST:event_cbxErrorActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void cbxDebugActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cbxDebugActionPerformed
        cbxDebug.setSelected(true);
        cbxError.setSelected(false);
        cbxFatal.setSelected(false);
        configLog4J();
    }                                                                            //GEN-LAST:event_cbxDebugActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void cmdDebugActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cmdDebugActionPerformed
        if (log.isDebugEnabled()) {
            log.debug("Debug");                                                  // NOI18N
        }
    }                                                                            //GEN-LAST:event_cmdDebugActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  args  the command line arguments
     */
    public static void main(final String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    new NewJFrame().setVisible(true);
                }
            });
    }

    /**
     * DOCUMENT ME!
     */
    private void configLog4J() {
        if (cbxDebug.isSelected()) {
            Log4JQuickConfig.configure4LumbermillOnLocalhost("DEBUG");
        } else if (cbxError.isSelected()) {
            Log4JQuickConfig.configure4LumbermillOnLocalhost("ERROR");
        } else {
            Log4JQuickConfig.configure4LumbermillOnLocalhost("DEBUG");
        }
    }
}
