/*
 * RoundedPanel.java
 *
 * Created on 18. Oktober 2007, 10:10
 */
package de.cismet.tools.gui;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Composite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;

/**
 *
 * @author  stefan
 */
public class SemiRoundedPanel extends javax.swing.JPanel {

    protected int curve = 20;
    protected int alpha = 0;

    /**
     * Creates new form RoundedPanel
     */
    public SemiRoundedPanel() {
        super();
        initComponents();
        setOpaque(false);
        this.setBackground(new Color(255, 255, 255));
    }
    public SemiRoundedPanel(Color color) {
        super();
        initComponents();
        setOpaque(false);
        this.setBackground(color);
    }

    public SemiRoundedPanel(LayoutManager layout) {
        super();
        setOpaque(false);
        initComponents();
        setLayout(layout);
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        final Graphics2D g2d = (Graphics2D) g;
        final Color old = g2d.getColor();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setColor(getBackground());
        g2d.fillRoundRect(0, 0, getWidth(), getHeight(), curve, curve);
        final Composite save = g2d.getComposite();
        g2d.setComposite(AlphaComposite.Src);
        g2d.fillRect(0, getHeight() - curve / 2, getWidth(), curve / 2);
        g2d.setComposite(save);
        g2d.setColor(old);
    }

    public int getAlpha() {
        return alpha;
    }

    public void setAlpha(int alpha) {
        this.alpha = alpha;
        setBackground(new Color(getBackground().getRed(), getBackground().getGreen(), getBackground().getBlue(), alpha));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
