/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * DocumentPanelTester.java
 *
 * Created on 26. August 2008, 12:56
 */
package de.cismet.tools.gui.documents;

import de.cismet.tools.gui.log4jquickconfig.Log4JQuickConfig;

/**
 * DOCUMENT ME!
 *
 * @author   hell
 * @version  $Revision$, $Date$
 */
public class DocumentPanelTester extends javax.swing.JFrame {

    //~ Instance fields --------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.tools.gui.documents.DocumentPanel dopTest;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form DocumentPanelTester.
     */
    public DocumentPanelTester() {
        Log4JQuickConfig.configure4LumbermillOnLocalhost();
        initComponents();
        dopTest.getDocumentListModel()
                .addElement(new DefaultDocument("briefpapier", "/home/hell/test/briefpapier.pdf"));                 // NOI18N
        dopTest.getDocumentListModel().addElement(new DefaultDocument("ein png", "/home/hell/test/cubert.png"));    // NOI18N
        dopTest.getDocumentListModel().addElement(new DefaultDocument("hiker (jpg)", "/home/hell/test/hiker.jpg")); // NOI18N
        dopTest.getDocumentListModel().addElement(new DefaultDocument("ein gif", "/home/hell/test/santa.gif"));     // NOI18N
        dopTest.getDocumentListModel()
                .addElement(new DefaultDocument(
                        "google online gif ",
                        "http://www.google.de/intl/de_de/images/logo.gif"));                                        // NOI18N
        dopTest.getDocumentListModel().addElement(new DefaultDocument("website", "http://www.ebay.de/"));           // NOI18N
        dopTest.getDocumentListModel()
                .addElement(new DefaultDocument(
                        "website",
                        "http://demohost/web/shen/utilities/wastewaterrecycling/SST-1.pdf"));                       // NOI18N
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        dopTest = new de.cismet.tools.gui.documents.DocumentPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(dopTest, java.awt.BorderLayout.CENTER);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  args  the command line arguments
     */
    public static void main(final String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    new DocumentPanelTester().setVisible(true);
                }
            });
    }
}
